language: php

services:
  - memcached

env:
  global:
    - MEMCACHE_HOST=127.0.0.1
    - MEMCACHE_PORT=11211

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
      env: PHPCS=true
    - php: 7.1
    - php: 7.2
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - phpenv version-name | grep ^5.[34] && echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true
  - phpenv version-name | grep ^5.[34] && echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - if [[ "$PHPCS" == "true" ]]; then vendor/bin/phpcs src --standard=coding_standard.xml -np; fi

after_success:
  # or enable logging
  - travis_retry php vendor/bin/coveralls

notifications:
  on_success: never
  on_failure: always

